### PR TITLE
use for_each instead of count to create resource

### PR DESCRIPTION
**Pull request by adrian-gierakowski**
This prevents unnecessary recreation of resources when content/order of the
names list changes.

Addresses issue mentioned in: https://github.com/terraform-google-modules/cloud-foundation-fabric/tree/73b7613cc062491305ebfabf8a8b1db0c53fc55b/foundations#things-to-be-aware-of

WARNING: this is a breaking change as the terraform state created before this
change will be incompatible with state expected after the change. This can
be fixed with `terraform state mv`.

### CODE REVIEW

**Comment by adrian-gierakowski** [comment]
this is similar to https://github.com/terraform-google-modules/terraform-google-folders/pull/21

**Comment by ludoo** [comment]
Adrian, can you make sure tests pass? I know it's kind of a bother, but it's pretty important especially when doing breaking changes and setting a new baseline.

**Comment by adrian-gierakowski** [comment]
Yes, sure. Will try to fix it later today.

**Comment by adrian-gierakowski** [comment]
@ludoo so the tests pass, but I had to patch the gcr/images/cloud-foundation-cicd/cft/kitchen-terraform image locally since the latest available version ([2.4.0](https://console.cloud.google.com/gcr/images/cloud-foundation-cicd/GLOBAL/cft/kitchen-terraform@sha256:c66fa37af4233944b90732d69795e891f0cfb879bc1137140af0b5c79afb87c7/details?tab=info)) comes with terraform 0.12.3 which has no support for `for_each` in resources. I guess someone is going to have to push a new version of the test image

**Comment by morgante** [comment]
@adrian-gierakowski We should switch to using the devtools image, which has support for Terraform 0.12.6. Ex. https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/Makefile#L22

**Comment by adrian-gierakowski** [comment]
not sure why it's failing this time, maybe someone with access to cloudbuild logs can pick this up

**Comment by ludoo** [comment]
> not sure why it's failing this time, maybe someone with access to cloudbuild logs can pick this up

The Cloud Build trigger is looking for a missing cloudbuild.yaml file. @averbuks can you check it out?

**Comment by averbuks** [comment]
@ludoo @adrian-gierakowski it's failing because that repo is still using "old way" of testing, I will take it #7

**Comment by averbuks** [comment]
@adrian-gierakowski  looks really good, could you pls add that change as unreleased to the [CHANGELOG](./CHANGELOG.md)

**Comment by averbuks** [comment]
> @adrian-gierakowski looks really good, could you pls add that change as unreleased to the [CHANGELOG](https://github.com/terraform-google-modules/terraform-google-service-accounts/blob/master/CHANGELOG.md)

I hope you don't mind I did it myself

**Comment by benesis002** [comment]
UP, can you merge this PR ?
It's very better to use for_each instead of count with Terraform 0.12

**Pull request merged**
